name = "NibblCraft"
author = "Majonez57"
version = "2.1.0"
description = "NibblCraft is a small modpack for frens"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da4d3fa60877296ebb023103159d410a71b361b491948c615da3454046ed96dd"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
