name = "NibblCraft"
author = "Majonez57"
version = "2.0.1"
description = "Nibblcraft is a small modpack for frens"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab9487c3e57fd8b4731a67e64fbc72377ea8ca8a16bed525d4e75385ebb59c3a"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
