name = "NibblCraft"
author = "Majonez57"
version = "2.1.0"
description = "NibblCraft is a small modpack for frens"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38c7af11db07732deb7886da1ab4ed540ae6701c29e40b6a9441b82174749eba"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"
