name = "NibblCraft"
author = "Majonez57"
version = "1.0.1"
description = "Nibblcraft is a small modpack for frens"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a22e1307773a668111ca836d57cf66014b160f1dd7bf260e6d332e106220fc1f"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
