name = "NibblCraft"
author = "Majonez57"
version = "2.0.1"
description = "Nibblcraft is a small modpack for frens"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec6c321e16a5cea88629d047483a30bde789290db9d85e0846ebd9a394773f7c"

[versions]
forge = "40.1.60"
minecraft = "1.18.2"
