
#Here are configs that need reloading to take effect
[general]
	#Enable Creative Tab
	creative_tab = false
	#Set to false to disable custom dispenser behaviors (i.e: filling jars) if for some reason they are causing trouble
	dispensers = false
	#Creates a creative tab full of filled jars
	jar_tab = false
	#Enables custom Configured config screen
	custom_configured_screen = true
	#Save generated resources to disk in a 'debug' folder in your game directory. Mainly for debug purposes but can be used to generate assets in all wood types for your mods :0
	debug_save_dynamic_pack = false

[blocks]
	planter = true
	clock_block = false
	pedestal = true
	wind_vane = true
	redstone_illuminator = true
	notice_board = true
	crank = false
	jar = true
	faucet = false
	turn_table = false
	spring_launcher = false
	speaker_block = true
	sign_post = true
	hanging_sign = true
	bellows = false
	sconce = true
	sconce_green = false
	cage = true
	item_shelf = true
	sconce_lever = true
	cog_block = false
	globe = true
	hourglass = true
	sack = false
	blackboard = true
	safe = false
	copper_lantern = true
	gold_trapdoor = true
	gold_door = true
	bamboo_spikes = true
	bamboo_spikes_tipped = true
	stone_lamp = true
	end_stone_lamp = true
	blackstone_lamp = true
	deepslate_lamp = true
	checker_block = true
	netherite_door = false
	netherite_trapdoor = false
	lock_block = false
	flax = true
	rope = true
	pulley_block = false
	fodder = false
	crimson_lantern = true
	magma_cream_block = false
	daub = true
	wattle_and_daub = true
	timber_frame = true
	flag = true
	stone_tile = true
	goblet = true
	raked_gravel = true
	statue = true
	iron_gate = true
	feather_block = true
	flint_block = true
	urn = true
	ash = true
	ash_bricks = true
	doormat = true
	flower_box = true
	blackstone_tile = true
	globe_sepia = true
	present = true
	sugar_cube = true
	lapis_bricks = true
	relayer = false
	crystal_display = true
	candle_holder = true
	silver_trapdoor = false
	silver_door = false
	lead_trapdoor = false
	lead_door = false

[items]
	flute = true
	stasis = false
	dispenser_minecart = false
	soap = true
	bubble_blower = true
	antique_ink = true
	shulker_shell = true
	candy = true
	wrench = false
	slingshot = false
	rope_arrow = true
	bomb = true
	pancake = true
	quiver = true

